/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package computergraphics;
import _3dsection.*;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.Box;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.Timer;
import javax.swing.UIManager;

/**
 *
 * @author AnThien049
 */
public class MainWindow extends javax.swing.JFrame{

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {       
        settingUpContentPaneBackground();
        initComponents();           
        System.out.println(this.LayeredDrawingPane.getSize());
        System.out.println(this.DrawingPane2D.getSize());
        System.out.println(this.DrawingPane3D.getSize());
        System.out.println(this.getSize());
        try  {
            settingUpSomeFunctionalities();
            customMenubar();
            customChoosingShapesActionsBar();
            customStatusBar();
        } catch (Exception e){  
            System.out.println(e);
        }           
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        SttBar = new javax.swing.JPanel()
        {
            @Override
            public void paintComponent(Graphics g) 
            {
                super.paintComponent(g);
                g.setColor(Color.WHITE);
                g.setFont(new Font("HACKED", Font.BOLD, 14));
                g.drawString("Hello From D17DQCN01", grtLocation, 22);
            }
        };
        btnQtmInfo = new javax.swing.JButton();
        ModeStatusBar = new javax.swing.JPanel();
        lblModeStatus = new javax.swing.JLabel();
        lblModeStatusValue = new javax.swing.JLabel();
        LayeredDrawingPane = new javax.swing.JLayeredPane();
        DrawingPane2D = new javax.swing.JPanel()
        {
            @Override
            public void paintComponent(Graphics g) 
            {
                super.paintComponent(g);
                if(start == true || pause == true)
                {
                    //newCar = new Car(new Point(location, 250));  
                    Graphics2D grp = (Graphics2D) g;
                    grp.setStroke(new BasicStroke(5));
                    DrawCar draw = new DrawCar(newCar);
                    draw.drawing(grp, Color.RED);
                }
            }
        };
        GridPane = new javax.swing.JPanel()
        {
            @Override
            public void paintComponent(Graphics g) 
            {
                super.paintComponent(g);
                Graphics2D grp = (Graphics2D) g;
                grp.setColor(Color.LIGHT_GRAY);
                grp.setStroke(new BasicStroke(1));
                for (int width = 0; width < GridPane.getWidth(); width += 5) {
                    grp.drawLine(width, 0, width, GridPane.getHeight());
                    if (width < GridPane.getHeight()) {
                        grp.drawLine(0, width, GridPane.getWidth(), width);
                    }          
                }
                grp.setStroke(new BasicStroke(5));
                grp.setColor(Color.BLUE);
                grp.drawLine(0, 250 + 2, GridPane.getWidth(), 250 + 2);
                grp.drawLine(400 + 2, 0, 400 + 2, GridPane.getHeight());
            }
        };
        DrawingPane3D = new javax.swing.JPanel()
        {
            @Override
            public void paintComponent(Graphics g) 
            {
                super.paintComponent(g);
                Graphics2D grp = (Graphics2D)g;
                grp.setStroke(new BasicStroke(5)); 
                grp.setColor(Color.BLUE);
                grp.drawLine(400 + 2, 0, 400 + 2, 250);
                grp.drawLine(400 + 2, 250 + 2, 800 + 2, 250 + 2);
                grp.drawLine(400 + 3, 250, 155 + 2, 500);
                Line lineObj = new Line(new Point(400 + 2, 250), new Point(400 + 2, 500));
                lineObj.drawDashedLinebyDDA(grp, 5, 10);
                lineObj = new Line(new Point(400, 250 + 2), new Point(0, 250 + 2));
                lineObj.drawDashedLinebyDDA(grp, 5, 10);
                //lineObj = new Line(new Point(400, 250), new Point(650, 0));
                //lineObj.drawDashedLinebyDDA(grp, 5, 4);
                //lineObj.drawLine(grp);
                GrAdEx ga = new GrAdEx();
                ga.setGraphicAdapter(g);
                switch(chosenShape){
                    case 1:
                    MyCube cb = new MyCube();
                    cb.makeCube(_3dSize.getX(), _3dSize.getY(), _3dSize.getZ());                                
                    cb.draw(ga);
                    break;
                    case 2:
                    MyPyramid prm = new MyPyramid();
                    prm.makePyramid(_3dSize.getX(), _3dSize.getY(), _3dSize.getZ());
                    prm.draw(ga);
                }

            }
        };
        PropertiesPane = new javax.swing.JTabbedPane();
        tabCar = new javax.swing.JPanel();
        LocationPane = new javax.swing.JPanel();
        XLocation = new javax.swing.JPanel();
        lblLocationXLabel = new javax.swing.JLabel();
        txtFLocationXValue = new javax.swing.JTextField();
        YLocation = new javax.swing.JPanel();
        lblLocationYLabel = new javax.swing.JLabel();
        txtFLocationYValue = new javax.swing.JTextField();
        SpeedPane = new javax.swing.JPanel();
        sldSpeed = new javax.swing.JSlider();
        lblSpeedFPMs = new javax.swing.JLabel();
        tab2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        ShapeActionContainerPane = new javax.swing.JPanel();
        ShapeAction2DContainerPane = new javax.swing.JPanel();
        shapesChoosingBar = new javax.swing.JPanel();
        btnCar = new javax.swing.JButton();
        actionChoosingBar = new javax.swing.JPanel();
        btnPlay = new javax.swing.JButton();
        btnGrid = new javax.swing.JButton();
        separator = new javax.swing.JPanel();
        ShapeAction3DContainerPane = new javax.swing.JPanel();
        btnCube = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnPyramid = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        mbFileMenu = new javax.swing.JMenu();
        saveMenuItem = new javax.swing.JMenuItem();
        mbModeMenu = new javax.swing.JMenu();
        _2DMenuItem = new javax.swing.JMenuItem();
        _3DMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Computer Graphics");
        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(1007, 623));
        setMinimumSize(new java.awt.Dimension(1007, 623));
        setResizable(false);

        SttBar.setBackground(new java.awt.Color(0, 122, 204));
        SttBar.setLayout(null);

        btnQtmInfo.setToolTipText("Information");
        btnQtmInfo.setBorderPainted(false);
        btnQtmInfo.setContentAreaFilled(false);
        btnQtmInfo.setFocusable(false);
        btnQtmInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQtmInfoMouseClicked(evt);
            }
        });
        SttBar.add(btnQtmInfo);
        btnQtmInfo.setBounds(978, 5, 22, 20);

        ModeStatusBar.setBackground(new java.awt.Color(0, 122, 204));
        ModeStatusBar.setForeground(new java.awt.Color(255, 255, 255));
        ModeStatusBar.setToolTipText("Current dimensional mode");
        ModeStatusBar.setPreferredSize(new java.awt.Dimension(90, 16));
        java.awt.GridBagLayout StatusBarLayout = new java.awt.GridBagLayout();
        StatusBarLayout.rowWeights = new double[] {10.0};
        ModeStatusBar.setLayout(StatusBarLayout);

        lblModeStatus.setBackground(new java.awt.Color(0, 0, 0));
        lblModeStatus.setForeground(new java.awt.Color(255, 255, 255));
        lblModeStatus.setText("Mode status:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 0, 2);
        ModeStatusBar.add(lblModeStatus, gridBagConstraints);

        lblModeStatusValue.setBackground(new java.awt.Color(0, 0, 0));
        lblModeStatusValue.setForeground(new java.awt.Color(255, 255, 255));
        lblModeStatusValue.setText("2D");
        lblModeStatusValue.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 0, 0);
        ModeStatusBar.add(lblModeStatusValue, gridBagConstraints);

        SttBar.add(ModeStatusBar);
        ModeStatusBar.setBounds(798, 7, 92, 16);

        LayeredDrawingPane.setBackground(new java.awt.Color(255, 255, 255));
        LayeredDrawingPane.setMaximumSize(new java.awt.Dimension(800, 500));
        LayeredDrawingPane.setMinimumSize(new java.awt.Dimension(800, 500));
        LayeredDrawingPane.setLayout(new java.awt.CardLayout());

        DrawingPane2D.setBackground(new java.awt.Color(255, 255, 255));
        DrawingPane2D.setMaximumSize(new java.awt.Dimension(800, 500));
        DrawingPane2D.setMinimumSize(new java.awt.Dimension(800, 500));
        DrawingPane2D.setPreferredSize(new java.awt.Dimension(800, 500));

        javax.swing.GroupLayout DrawingPane2DLayout = new javax.swing.GroupLayout(DrawingPane2D);
        DrawingPane2D.setLayout(DrawingPane2DLayout);
        DrawingPane2DLayout.setHorizontalGroup(
            DrawingPane2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        DrawingPane2DLayout.setVerticalGroup(
            DrawingPane2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        LayeredDrawingPane.add(DrawingPane2D, "card2");

        GridPane.setBackground(new java.awt.Color(255, 255, 255));
        GridPane.setMaximumSize(new java.awt.Dimension(800, 500));
        GridPane.setMinimumSize(new java.awt.Dimension(800, 500));
        GridPane.setPreferredSize(new java.awt.Dimension(800, 500));

        javax.swing.GroupLayout GridPaneLayout = new javax.swing.GroupLayout(GridPane);
        GridPane.setLayout(GridPaneLayout);
        GridPaneLayout.setHorizontalGroup(
            GridPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        GridPaneLayout.setVerticalGroup(
            GridPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        LayeredDrawingPane.add(GridPane, "card4");

        DrawingPane3D.setBackground(new java.awt.Color(255, 255, 255));
        DrawingPane3D.setMaximumSize(new java.awt.Dimension(800, 500));
        DrawingPane3D.setMinimumSize(new java.awt.Dimension(800, 500));
        DrawingPane3D.setPreferredSize(new java.awt.Dimension(800, 500));

        javax.swing.GroupLayout DrawingPane3DLayout = new javax.swing.GroupLayout(DrawingPane3D);
        DrawingPane3D.setLayout(DrawingPane3DLayout);
        DrawingPane3DLayout.setHorizontalGroup(
            DrawingPane3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        DrawingPane3DLayout.setVerticalGroup(
            DrawingPane3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        LayeredDrawingPane.add(DrawingPane3D, "card3");

        PropertiesPane.setBackground(new java.awt.Color(39, 45, 48));
        PropertiesPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Properties", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("HACKED", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        PropertiesPane.setForeground(new java.awt.Color(39, 45, 48));
        PropertiesPane.setFont(new java.awt.Font("VNI-Whimsy", 0, 12)); // NOI18N

        tabCar.setBackground(new java.awt.Color(255, 255, 255));
        tabCar.setForeground(new java.awt.Color(0, 0, 0));
        tabCar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        LocationPane.setBackground(new java.awt.Color(255, 255, 255));
        LocationPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Location", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("HACKED", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        LocationPane.setForeground(new java.awt.Color(0, 0, 0));
        LocationPane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        XLocation.setBackground(new java.awt.Color(255, 255, 255));
        XLocation.setForeground(new java.awt.Color(0, 0, 0));
        XLocation.setPreferredSize(new java.awt.Dimension(70, 40));

        lblLocationXLabel.setBackground(new java.awt.Color(255, 255, 255));
        lblLocationXLabel.setFont(new java.awt.Font("HACKED", 1, 14)); // NOI18N
        lblLocationXLabel.setForeground(new java.awt.Color(0, 0, 0));
        lblLocationXLabel.setText("X :");
        lblLocationXLabel.setMinimumSize(new java.awt.Dimension(35, 16));
        lblLocationXLabel.setPreferredSize(new java.awt.Dimension(18, 16));
        XLocation.add(lblLocationXLabel);

        txtFLocationXValue.setMinimumSize(new java.awt.Dimension(35, 24));
        txtFLocationXValue.setPreferredSize(new java.awt.Dimension(35, 24));
        txtFLocationXValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFLocationXValueActionPerformed(evt);
            }
        });
        XLocation.add(txtFLocationXValue);

        LocationPane.add(XLocation);

        YLocation.setBackground(new java.awt.Color(255, 255, 255));
        YLocation.setForeground(new java.awt.Color(0, 0, 0));
        YLocation.setMinimumSize(new java.awt.Dimension(70, 40));
        YLocation.setPreferredSize(new java.awt.Dimension(70, 40));

        lblLocationYLabel.setBackground(new java.awt.Color(255, 255, 255));
        lblLocationYLabel.setFont(new java.awt.Font("HACKED", 1, 14)); // NOI18N
        lblLocationYLabel.setForeground(new java.awt.Color(0, 0, 0));
        lblLocationYLabel.setText("Y :");
        lblLocationYLabel.setPreferredSize(new java.awt.Dimension(18, 16));
        YLocation.add(lblLocationYLabel);

        txtFLocationYValue.setMinimumSize(new java.awt.Dimension(35, 24));
        txtFLocationYValue.setPreferredSize(new java.awt.Dimension(35, 24));
        txtFLocationYValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFLocationYValueActionPerformed(evt);
            }
        });
        YLocation.add(txtFLocationYValue);

        LocationPane.add(YLocation);

        SpeedPane.setBackground(new java.awt.Color(255, 255, 255));
        SpeedPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Speed", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("HACKED", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        SpeedPane.setForeground(new java.awt.Color(0, 0, 0));
        SpeedPane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 13));

        sldSpeed.setMajorTickSpacing(10);
        sldSpeed.setMinimum(20);
        sldSpeed.setMinorTickSpacing(1);
        sldSpeed.setPaintTicks(true);
        sldSpeed.setValue(80);
        sldSpeed.setPreferredSize(new java.awt.Dimension(130, 16));
        sldSpeed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldSpeedStateChanged(evt);
            }
        });
        SpeedPane.add(sldSpeed);

        lblSpeedFPMs.setPreferredSize(new java.awt.Dimension(30, 16));
        SpeedPane.add(lblSpeedFPMs);

        javax.swing.GroupLayout tabCarLayout = new javax.swing.GroupLayout(tabCar);
        tabCar.setLayout(tabCarLayout);
        tabCarLayout.setHorizontalGroup(
            tabCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LocationPane, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(SpeedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                .addContainerGap())
        );
        tabCarLayout.setVerticalGroup(
            tabCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCarLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(LocationPane, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(SpeedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(247, Short.MAX_VALUE))
        );

        PropertiesPane.addTab("Car", null, tabCar, "");

        javax.swing.GroupLayout tab2Layout = new javax.swing.GroupLayout(tab2);
        tab2.setLayout(tab2Layout);
        tab2Layout.setHorizontalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );
        tab2Layout.setVerticalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        PropertiesPane.addTab("sth else", tab2);

        jButton1.setText("Click me");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ShapeActionContainerPane.setOpaque(false);
        ShapeActionContainerPane.setLayout(new java.awt.CardLayout());

        ShapeAction2DContainerPane.setOpaque(false);
        ShapeAction2DContainerPane.setLayout(null);

        shapesChoosingBar.setOpaque(false);
        shapesChoosingBar.setLayout(null);

        btnCar.setBorderPainted(false);
        btnCar.setContentAreaFilled(false);
        btnCar.setFocusPainted(false);
        btnCar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCarMouseClicked(evt);
            }
        });
        btnCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarActionPerformed(evt);
            }
        });
        shapesChoosingBar.add(btnCar);
        btnCar.setBounds(10, 8, 45, 45);

        ShapeAction2DContainerPane.add(shapesChoosingBar);
        shapesChoosingBar.setBounds(0, 0, 482, 56);

        actionChoosingBar.setOpaque(false);

        btnPlay.setToolTipText("Play/Stop animation (S)");
        btnPlay.setBorderPainted(false);
        btnPlay.setContentAreaFilled(false);
        btnPlay.setFocusable(false);
        btnPlay.setMaximumSize(new java.awt.Dimension(40, 40));
        btnPlay.setMinimumSize(new java.awt.Dimension(40, 40));
        btnPlay.setPreferredSize(new java.awt.Dimension(40, 40));
        btnPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlayMouseClicked(evt);
            }
        });

        btnGrid.setToolTipText("Show Grid (G)");
        btnGrid.setFocusPainted(false);
        btnGrid.setPreferredSize(new java.awt.Dimension(40, 40));
        btnGrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGridActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout actionChoosingBarLayout = new javax.swing.GroupLayout(actionChoosingBar);
        actionChoosingBar.setLayout(actionChoosingBarLayout);
        actionChoosingBarLayout.setHorizontalGroup(
            actionChoosingBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionChoosingBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(btnGrid, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        actionChoosingBarLayout.setVerticalGroup(
            actionChoosingBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, actionChoosingBarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(actionChoosingBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrid, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        ShapeAction2DContainerPane.add(actionChoosingBar);
        actionChoosingBar.setBounds(592, 0, 202, 50);

        separator.setBackground(new java.awt.Color(255, 255, 255));
        separator.setPreferredSize(new java.awt.Dimension(3, 67));

        javax.swing.GroupLayout separatorLayout = new javax.swing.GroupLayout(separator);
        separator.setLayout(separatorLayout);
        separatorLayout.setHorizontalGroup(
            separatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        separatorLayout.setVerticalGroup(
            separatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        ShapeAction2DContainerPane.add(separator);
        separator.setBounds(577, 8, 3, 42);

        ShapeActionContainerPane.add(ShapeAction2DContainerPane, "card2");

        ShapeAction3DContainerPane.setOpaque(false);

        btnCube.setBorderPainted(false);
        btnCube.setContentAreaFilled(false);
        btnCube.setFocusPainted(false);
        btnCube.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCubeMouseClicked(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnPyramid.setBorderPainted(false);
        btnPyramid.setContentAreaFilled(false);
        btnPyramid.setFocusPainted(false);
        btnPyramid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPyramidMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ShapeAction3DContainerPaneLayout = new javax.swing.GroupLayout(ShapeAction3DContainerPane);
        ShapeAction3DContainerPane.setLayout(ShapeAction3DContainerPaneLayout);
        ShapeAction3DContainerPaneLayout.setHorizontalGroup(
            ShapeAction3DContainerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShapeAction3DContainerPaneLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnCube, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPyramid, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(445, Short.MAX_VALUE))
        );
        ShapeAction3DContainerPaneLayout.setVerticalGroup(
            ShapeAction3DContainerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShapeAction3DContainerPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ShapeAction3DContainerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPyramid, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCube, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        ShapeActionContainerPane.add(ShapeAction3DContainerPane, "card3");

        mbFileMenu.setText("File");
        mbFileMenu.setToolTipText("Some specific tasks");
        mbFileMenu.setFont(new java.awt.Font("HACKED", 0, 12)); // NOI18N

        saveMenuItem.setFont(new java.awt.Font("HACKED", 1, 12)); // NOI18N
        saveMenuItem.setText("Save");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        mbFileMenu.add(saveMenuItem);

        MenuBar.add(mbFileMenu);

        mbModeMenu.setText("Mode");
        mbModeMenu.setToolTipText("Select dimensional mode");
        mbModeMenu.setFont(new java.awt.Font("HACKED", 0, 12)); // NOI18N

        _2DMenuItem.setBackground(new java.awt.Color(255, 255, 255));
        _2DMenuItem.setFont(new java.awt.Font("HACKED", 1, 12)); // NOI18N
        _2DMenuItem.setText("2D");
        _2DMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _2DMenuItemActionPerformed(evt);
            }
        });
        mbModeMenu.add(_2DMenuItem);

        _3DMenuItem.setBackground(new java.awt.Color(255, 255, 255));
        _3DMenuItem.setFont(new java.awt.Font("HACKED", 1, 12)); // NOI18N
        _3DMenuItem.setText("3D");
        _3DMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _3DMenuItemActionPerformed(evt);
            }
        });
        mbModeMenu.add(_3DMenuItem);

        MenuBar.add(mbModeMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SttBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LayeredDrawingPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShapeActionContainerPane, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(41, 41, 41))
                    .addComponent(PropertiesPane)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ShapeActionContainerPane, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PropertiesPane, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(LayeredDrawingPane, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SttBar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="Components Action Performing"> 
    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        JOptionPane.showMessageDialog(this, "wanna save?", "Save", JOptionPane.QUESTION_MESSAGE);
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void _2DMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__2DMenuItemActionPerformed
        System.out.println("2D mode selected");
        this.lblModeStatusValue.setText("2D");
        this.DrawingPane2D.setVisible(true);
        this.DrawingPane2D.setOpaque(true);
        this.ShapeAction2DContainerPane.setVisible(true);
        this.GridPane.setVisible(false);
        this.DrawingPane3D.setVisible(false); 
        this.ShapeAction3DContainerPane.setVisible(false);
        if(gridAvailable == true){
          //  this.DrawingPane2D.setVisible(false);
            this.GridPane.setVisible(true);   
            this.DrawingPane2D.setVisible(true);
            this.DrawingPane2D.setOpaque(false);
            gridAvailable = true;
        }      
    }//GEN-LAST:event__2DMenuItemActionPerformed

    private void _3DMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__3DMenuItemActionPerformed
        System.out.println("3D mode selected");
        this.lblModeStatusValue.setText("3D");
        this.DrawingPane3D.setVisible(true);
        this.ShapeAction3DContainerPane.setVisible(true);
        this.GridPane.setVisible(false);
        this.DrawingPane2D.setVisible(false);
        this.ShapeAction2DContainerPane.setVisible(false);
    }//GEN-LAST:event__3DMenuItemActionPerformed

    private void btnGridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGridActionPerformed
        if(gridAvailable == false){
            System.out.println("Grid Enabled");
            this.DrawingPane3D.setVisible(false);   
            this.GridPane.setVisible(true);   
            this.DrawingPane2D.setVisible(true);
            this.DrawingPane2D.setOpaque(false);
            gridAvailable = true;
            location -= step;
            this.DrawingPane2D.repaint();
        }else{
            System.out.println("Grid Disabled");
            location -= step;
            this.DrawingPane2D.repaint();
            this.GridPane.setVisible(false);   
            this.DrawingPane2D.setVisible(true);
            this.DrawingPane2D.setOpaque(true);
            gridAvailable = false;
        }             
    }//GEN-LAST:event_btnGridActionPerformed

    private void btnCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarActionPerformed
        //System.out.println("??");      
        if (start == true) {
            newCar = new Car(new Point(location, startLocationY));
            this.txtFLocationXValue.setText(String.valueOf(scaledX(newCar.get1stPoint().getX())));
            this.txtFLocationYValue.setText(String.valueOf(scaledY(newCar.get1stPoint().getY())));
            this.lblSpeedFPMs.setText(String.valueOf(this.sldSpeed.getValue()));
           // System.out.println(location);
            if (runBackX == true) {                
                this.DrawingPane2D.repaint();
                location -= step;
                if (location <= startLocationX) {
                    if(startLocationY >= downStopLocationY){
                        startLocationY -= step * 3;
                    }else if (startLocationY <= upStopLocationY){
                        startLocationY += step * 3;
                    } 
                    runBackX = false;
                }
            } else {
                this.DrawingPane2D.repaint();
                location += step;
                if (location >= stopLocationX) {
                    if(startLocationY >= downStopLocationY){
                        startLocationY -= step * 3;
                    }else if (startLocationY <= upStopLocationY){
                        startLocationY += step * 3;
                    }                      
                    runBackX = true;
                }
            }
        }                
    }//GEN-LAST:event_btnCarActionPerformed
    
    private void btnCarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCarMouseClicked
        if (start == false) { 
            System.out.println("Draw car");
            start = true;
            location = startLocationX;
            newCar = new Car(new Point(location, startLocationY));
            this.DrawingPane2D.repaint();
            this.txtFLocationXValue.setText(String.valueOf(scaledX(newCar.get1stPoint().getX())));
            this.txtFLocationYValue.setText(String.valueOf(scaledY(newCar.get1stPoint().getY())));
            location += step;   
            exist = true;
    }//GEN-LAST:event_btnCarMouseClicked
}
    private void btnPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayMouseClicked
        timerDelay = 100 - this.sldSpeed.getValue();
        if(start == false || exist == true){
            System.out.println("Play animation");
            start = true;
            timer = new Timer(timerDelay, this.btnCar.getActionListeners()[0]);
            timer.start();     
            exist = false;
        } else if (start == true) {
            System.out.println("Stop animation");
            start = false;   
            pause = true;
            timer.stop(); 
        }
        changePlayStopIcon();
    }//GEN-LAST:event_btnPlayMouseClicked

    private void btnQtmInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQtmInfoMouseClicked
        UIManager.put("OptionPane.messageFont", new Font("VNF-Valentina", Font.PLAIN, 15));
        UIManager.put("OptionPane.buttonFont", new Font("VNF-Valentina", Font.PLAIN, 15));       
//        JOptionPane.showMessageDialog(this, "N17DCCN008  Đinh Nguyễn Thiên Ân \n" 
//                                          + "N17DCCN013   Nguyễn Mạnh Bình \n"
//                                          + "N17DCCN042  Phạm Phan Đại Hải \n"
//                                          + "N17DCCN053  Trương Minh Hoàng \n"
//                                          + "N17DCCN056  Nguyễn Ngọc Huy",
//                                     "Thành Viên", JOptionPane.INFORMATION_MESSAGE, scaledPePeIcon);
        
        JOptionPane op = new JOptionPane("N17DCCN008  Đinh Nguyễn Thiên Ân \n" 
                                       + "N17DCCN013   Nguyễn Mạnh Bình \n"
                                       + "N17DCCN042  Phạm Phan Đại Hải \n"
                                       + "N17DCCN053  Trương Minh Hoàng \n"
                                       + "N17DCCN056  Lê Ngọc Huy"
                                       ,JOptionPane.INFORMATION_MESSAGE, JOptionPane.DEFAULT_OPTION, scaledPePeIcon); 
        op.setBackground(Color.WHITE);
        getComponents(op);
        JDialog dialog = op.createDialog(this, "Thành Viên");
        dialog.setAlwaysOnTop(true);
        dialog.setModal(false);
        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);      
        dialog.setVisible(true);
    }//GEN-LAST:event_btnQtmInfoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        gottaSeeitManxD();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //NhapToaDo3D ntd = new NhapToaDo3D("Cube");
        new GUI().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void sldSpeedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldSpeedStateChanged
        timerDelay = 100 - this.sldSpeed.getValue();
        this.lblSpeedFPMs.setText(String.valueOf(this.sldSpeed.getValue()));
        System.out.println(this.sldSpeed.getValue());
        if(timer != null){
            timer.stop();
            timer = new Timer(timerDelay, this.btnCar.getActionListeners()[0]);
            timer.start();
        }       
    }//GEN-LAST:event_sldSpeedStateChanged

    private void txtFLocationXValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFLocationXValueActionPerformed
        String x = this.txtFLocationXValue.getText();
        String y = this.txtFLocationYValue.getText();
        if(!x.isBlank() && !y.isBlank() && x.matches("-?\\d+") && y.matches("-?\\d+")){
            System.out.println("gg");
            location = xByScaledX(Integer.parseInt(x));
            startLocationY = yByScaleY(Integer.parseInt(y));
             {  
                start = true;
                exist = true;
                newCar = new Car(new Point(location, startLocationY));
                this.DrawingPane2D.repaint();
                location += step;     
            }
            //start = false;
        }else{
            JOptionPane.showMessageDialog(this, "Giá trị không hợp lệ", "Invalid value", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtFLocationXValueActionPerformed

    private void txtFLocationYValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFLocationYValueActionPerformed
        txtFLocationXValueActionPerformed(evt);
    }//GEN-LAST:event_txtFLocationYValueActionPerformed

    private void btnCubeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCubeMouseClicked
        chosenShape = 1;
        JTextField xField = new JTextField(5);
        JTextField yField = new JTextField(5);
        JTextField zField = new JTextField(5);
        
        JPanel myPanel = new JPanel();
        myPanel.add(new JLabel("Nhập x:"));
        myPanel.add(xField);
        myPanel.add(new JLabel("Nhập y:"));
        myPanel.add(yField);
        myPanel.add(new JLabel("Nhập z:"));
        myPanel.add(zField);

        int result = JOptionPane.showConfirmDialog(this, myPanel, "Nhập tọa độ X and Y and Z", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
            _3dSize.setX(Integer.parseInt(xField.getText()));
            _3dSize.setY(Integer.parseInt(yField.getText()));
            _3dSize.setZ(Integer.parseInt(zField.getText()));
        }
        this.DrawingPane3D.repaint();
    }//GEN-LAST:event_btnCubeMouseClicked

    private void btnPyramidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPyramidMouseClicked
        chosenShape = 2;
        JTextField xField = new JTextField(5);
        JTextField yField = new JTextField(5);
        JTextField zField = new JTextField(5);
        
        JPanel myPanel = new JPanel();
        myPanel.add(new JLabel("Nhập x:"));
        myPanel.add(xField);
        myPanel.add(new JLabel("Nhập y:"));
        myPanel.add(yField);
        myPanel.add(new JLabel("Nhập z:"));
        myPanel.add(zField);

        int result = JOptionPane.showConfirmDialog(this, myPanel, "Nhập tọa độ X and Y and Z", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
            _3dSize.setX(Integer.parseInt(xField.getText()));
            _3dSize.setY(Integer.parseInt(yField.getText()));
            _3dSize.setZ(Integer.parseInt(zField.getText()));
        }
        this.DrawingPane3D.repaint();
    }//GEN-LAST:event_btnPyramidMouseClicked
    // </editor-fold>          
    
    // <editor-fold defaultstate="collapsed" desc="Components Customizing"> 
    
    /**
     * Custom menu bar 
     */
    public void customMenubar() throws IOException
    { 
        /**
        * File menu  
        */
        this.mbFileMenu.setMnemonic(KeyEvent.VK_F);
        
        /**
        * File menu item: save
        */      
        ImageIcon icon = new ImageIcon("images/save_icon.png");
        Image image = icon.getImage();
        Image newImg = image.getScaledInstance(20, 20, java.awt.Image.SCALE_SMOOTH); 
        ImageIcon scaledSaveIcon = new ImageIcon(newImg);
        this.saveMenuItem.setIcon(scaledSaveIcon);
        this.saveMenuItem.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_S, KeyEvent.CTRL_DOWN_MASK));
        
        /**
        * Mode menu
        */
        this.mbModeMenu.setMnemonic(KeyEvent.VK_M);
        
        /**
        * Mode menu item: 2D
        */
        icon = new ImageIcon("images/2D_coordinate.png");
        image = icon.getImage();
        newImg = image.getScaledInstance(30, 30, java.awt.Image.SCALE_SMOOTH); 
        ImageIcon scaled2DIcon = new ImageIcon(newImg);
        this._2DMenuItem.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_2, KeyEvent.CTRL_DOWN_MASK));
        this._2DMenuItem.setIcon(scaled2DIcon);
        
        /**
        * Mode menu item: 3D
        */
        icon = new ImageIcon("images/3D_coordinate.png");
        image = icon.getImage(); 
        newImg = image.getScaledInstance(30, 30, java.awt.Image.SCALE_SMOOTH);  
        ImageIcon scaled3DIcon = new ImageIcon(newImg);
        this._3DMenuItem.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_3, KeyEvent.CTRL_DOWN_MASK));
        this._3DMenuItem.setIcon(scaled3DIcon);
    }
    
    /**
     * Custom shapes-choosing bar 
     */
    public void customChoosingShapesActionsBar()
    {
        ImageIcon icon = new ImageIcon("images/car_icon.png");
        Image image = icon.getImage();
        Image newImg = image.getScaledInstance(this.btnCar.getWidth(), this.btnCar.getHeight(), java.awt.Image.SCALE_SMOOTH); 
        ImageIcon scaledCarIcon = new ImageIcon(newImg);
        this.btnCar.setIcon(scaledCarIcon);
        
        icon = new ImageIcon("images/play_icon.png");
        image = icon.getImage();
        newImg = image.getScaledInstance(this.btnPlay.getWidth(), this.btnPlay.getHeight(), java.awt.Image.SCALE_SMOOTH); 
        scaledPlayIcon = new ImageIcon(newImg);
        this.btnPlay.setIcon(scaledPlayIcon);
        
        icon = new ImageIcon("images/stop_icon.png");
        image = icon.getImage();
        newImg = image.getScaledInstance(this.btnPlay.getWidth(), this.btnPlay.getHeight(), java.awt.Image.SCALE_SMOOTH); 
        scaledStopIcon = new ImageIcon(newImg);
        
        icon = new ImageIcon("images/grid_icon.png");
        image = icon.getImage();
        newImg = image.getScaledInstance(this.btnGrid.getWidth(), this.btnGrid.getHeight(), java.awt.Image.SCALE_SMOOTH); 
        ImageIcon scaledGridIcon = new ImageIcon(newImg);
        this.btnGrid.setIcon(scaledGridIcon);
        
        icon = new ImageIcon("images/cube_icon.png");
        image = icon.getImage();
        newImg = image.getScaledInstance(this.btnCube.getWidth(), this.btnCube.getHeight(), java.awt.Image.SCALE_SMOOTH); 
        ImageIcon scaledCubeIcon = new ImageIcon(newImg);
        this.btnCube.setIcon(scaledCubeIcon);
        
        icon = new ImageIcon("images/pyramid_icon.png");
        image = icon.getImage();
        newImg = image.getScaledInstance(this.btnPyramid.getWidth(), this.btnPyramid.getHeight(), java.awt.Image.SCALE_SMOOTH); 
        ImageIcon scaledPyramidIcon = new ImageIcon(newImg);
        this.btnPyramid.setIcon(scaledPyramidIcon);
    }
    
    /**
     * Custom status bar 
     */
    public void customStatusBar()
    {
        ImageIcon icon = new ImageIcon("images/question_mark_icon.png");
        Image image = icon.getImage();
        Image newImg = image.getScaledInstance(this.btnQtmInfo.getWidth(), this.btnQtmInfo.getHeight(), java.awt.Image.SCALE_SMOOTH); 
        ImageIcon scaledQMIcon = new ImageIcon(newImg);
        this.btnQtmInfo.setIcon(scaledQMIcon);
        this.btnQtmInfo.setMnemonic(KeyEvent.VK_SLASH);  
        
        icon = new ImageIcon("images/meme28.png");
        image = icon.getImage();
        newImg = image.getScaledInstance(50, 50, java.awt.Image.SCALE_SMOOTH); 
        scaledPePeIcon = new ImageIcon(newImg);
    }
    
    /**
     * Custom some initialized components properties & functionalities
     */
    public void settingUpContentPaneBackground()
    {
        /**
        * Setting up some properties for main window
        */
        //this.getContentPane().setBackground(new Color(60, 63, 65)); // Set màu nền của contentPane của frame
        try {
            BufferedImage myImage = ImageIO.read(new File("images/bg.jpg"));
            Image bgrImage = myImage.getScaledInstance(1021, 669, java.awt.Image.SCALE_SMOOTH); 
            this.setContentPane(new BackgroundImage(bgrImage));      
        } catch(IOException e){System.out.println(e);}
    }
    
    public void settingUpSomeFunctionalities()
    {
      /**
        * Timer for some animations
        */
//        ActionListener greetingAction = new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent arg0) {
//                greeting();
//            }
//        };
//        
//        greetingTimer = new Timer(20, greetingAction);
//        greetingTimer.start();
         
        greetingTimer = new Timer(grtTimerDelay, new ActionListener(){    //Câu chào ở thanh status animation
        public void actionPerformed(ActionEvent e) {
            greeting();
        }
        });
        greetingTimer.start();
        
        /**
        * Key Binding for some functionalities
        */
        KeyStroke escapeKeyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0, false); //ESC để quit
        Action escapeAction = new AbstractAction() {
           public void actionPerformed(ActionEvent e) {
               // dispose();
                System.exit(0);
           }
        }; 
        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(escapeKeyStroke, "ESCAPE");
        this.getRootPane().getActionMap().put("ESCAPE", escapeAction);
        
        this.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_SPACE) {
                    System.out.println("rwebvb");
                    e.consume();
                }
            }
        });
        KeyStroke playStopKeyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_S, 0);  //S để play/stop animation
        Action playStopAction = new AbstractAction() {
           public void actionPerformed(ActionEvent e) {
                MouseEvent mEvt = null;
                btnPlayMouseClicked(mEvt);
           }    
        }; 
        this.btnPlay.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(playStopKeyStroke, "PLAYSTOP");
        this.btnPlay.getActionMap().put("PLAYSTOP", playStopAction);
        
        KeyStroke drawCarKeyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_C, 0);  //C để vẽ xe tĩnh
        Action drawCarAction = new AbstractAction() {
           public void actionPerformed(ActionEvent e) {
                MouseEvent mEvt = null;
                btnCarMouseClicked(mEvt);
           }    
        }; 
        this.btnCar.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(drawCarKeyStroke, "STATICDRAW");
        this.btnCar.getActionMap().put("STATICDRAW", drawCarAction);
        
        KeyStroke drawGridKeyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_G, 0);  //G để vẽ lưới tọa độ
        Action drawGridAction = new AbstractAction() {
           public void actionPerformed(ActionEvent e) {
                btnGridActionPerformed(e);
           }    
        }; 
        this.btnCar.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(drawGridKeyStroke, "DRAWGRID");
        this.btnCar.getActionMap().put("DRAWGRID", drawGridAction);
        
        KeyStroke memberInfoKeyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_SLASH, 0);  //nhấn /(?) để hiển thị thông tin thành viên
        Action memberInfoAction = new AbstractAction() {
           public void actionPerformed(ActionEvent e) {
                MouseEvent mEvt = null;
                btnQtmInfoMouseClicked(mEvt);
           }    
        }; 
        this.btnCar.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(memberInfoKeyStroke, "SHOWINFO");
        this.btnCar.getActionMap().put("SHOWINFO", memberInfoAction);
        
    }  
    
    /**
     * Some required processing for those above or just additional functionalities
     */
    public void clearDrawingPanel() // Làm mới drawing panel xóa ds các đối tượng đã được vẽ
    {
        Graphics2D grp = (Graphics2D)this.DrawingPane2D.getGraphics();
        grp.setBackground(Color.WHITE);    
    }
    
    public void changePlayStopIcon()
    {
        if(start == true){
            this.btnPlay.setIcon(scaledStopIcon);
        }else{
            this.btnPlay.setIcon(scaledPlayIcon);
        }     
    }
    
    public void greeting()
    {
        if (grtRunBack == true) {
            this.SttBar.repaint();
            grtLocation -= grtStep;
            if (grtLocation == 10) {
                grtRunBack = false;
            }
        } else {
            this.SttBar.repaint();
            grtLocation += grtStep;
            if (grtLocation == 633) {
                grtRunBack = true;
            }
        }  
    }
    
    public void getComponents(Container c) {
        Component[] m = c.getComponents();
        for (int i = 0; i < m.length; i++) {
            if (m[i].getClass().getName() == "javax.swing.JPanel")
            {
                m[i].setBackground(Color.WHITE);
            }
           // if (c.getClass().isInstance(m[i])) 
            getComponents((Container) m[i]);
        }
    }
    
    public void gottaSeeitManxD()
    {
        if(this.LayeredDrawingPane.isVisible()){
            this.LayeredDrawingPane.setVisible(false);
            this.PropertiesPane.setVisible(false);
            this.ShapeActionContainerPane.setVisible(false);
        }else{
            this.LayeredDrawingPane.setVisible(true);
            this.PropertiesPane.setVisible(true);
            this.ShapeActionContainerPane.setVisible(true);
        }        
    }
             
//    public void drawGrid()
//    {
//        Graphics2D grp = (Graphics2D) this.GridPane.getGraphics();
//        grp.setColor(Color.LIGHT_GRAY);
//        grp.setStroke(new BasicStroke(1));
//        for (int width = 0; width < this.GridPane.getWidth(); width += 6) {
//                grp.drawLine(width, 0, width, this.GridPane.getHeight());
//                if (width < this.GridPane.getHeight()) {
//                grp.drawLine(0, width, this.GridPane.getWidth(), width);
//            }          
//        }
//        grp.setColor(Color.RED);
//        grp.drawLine(0, this.GridPane.getHeight()/2 + 6, this.GridPane.getWidth(), this.GridPane.getHeight()/2 + 6);
//        grp.drawLine(this.GridPane.getWidth()/2 + 2, 0, this.GridPane.getWidth()/2 + 2, this.GridPane.getHeight());
//    }
    // </editor-fold> 
    
    // <editor-fold defaultstate="collapsed" desc="Some math calculations">
    public int round(float num) {
        return (int) (num + 0.5);
    }

    public int scaledX(double originalValue) // trả về tọa độ X (làm tròn) theo tỉ lệ 5:1 với gốc TD 400;250
    {
        if (originalValue < originX) {
            return (int) ((originalValue - originX) / 5 - 0.5);
        } else {
            return (int) ((originalValue - originX) / 5 + 0.5);
        }
    }

    public int scaledY(double originalValue) // trả về tọa độ Y (làm tròn) theo tỉ lệ 5:1 với gốc TD 400;250
    {
        if (originalValue < originY) {
            return (-1) * (int) ((originalValue - originY) / 5 - 0.5);
        } else {
            return (-1) * (int) ((originalValue - originY) / 5 + 0.5);
        }
    }

    public int xByScaledX(double originalValue) // trả về tọa độ X gốc được làm tròn chia hết cho 5 (tọa độ ứng với từng mốc scale)
    {
        return originX + 5 * (int)originalValue + 2/*scaledX(originalValue)*/;
    }

    public int yByScaleY(double originalValue) // trả về tọa độ Y gốc được làm tròn chia hết cho 5 (tọa độ ứng với từng mốc scale)
    {
        return originY - 5 * (int)originalValue + 2/*scaledY(originalValue)*/;
    }

//    public Point pointByScale(Point orgPoint) {
//        int xScaled = xByScaleX(orgPoint.getX());
//        int yScaled = yByScaleY(orgPoint.getY());
//        return new Point(xScaled, yScaled);
//    }
//
    public int reverseScale(int scaleValue) {
        return 5 * scaleValue + 3;
    }
    // </editor-fold> 
    
    
    // <editor-fold defaultstate="collapsed" desc="Global User-defined variables declaration">   
    int originX = 400;   // tâm X
    int originY = 250;   // tâm Y
    
    int location = 20 - 3;
    int startLocationX = 20 - 3;
    int stopLocationX = 550 - 3;
    int upStopLocationY = 100;
    int downStopLocationY = 400;
    int step = 5;   
    int timerDelay;
    int startLocationY = 290 + 2;
    boolean start = false;
    boolean runBackX = false;
    boolean runBackY = false;
    boolean exist = false;
    boolean pause = false;
    Timer timer = null;
    
    int grtLocation = 3;
    int grtStep = 1;
    int grtTimerDelay = 10;
    boolean grtRunBack = false; 
    Timer greetingTimer;
     
    ImageIcon scaledStopIcon = null;
    ImageIcon scaledPlayIcon = null;
    ImageIcon scaledPePeIcon = null;
    
    Car newCar;
    
    int chosenShape = 0;
    boolean gridAvailable = false;
    _3dShapesSize _3dSize = new _3dShapesSize();
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Global application variables declaration">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DrawingPane2D;
    private javax.swing.JPanel DrawingPane3D;
    private javax.swing.JPanel GridPane;
    private javax.swing.JLayeredPane LayeredDrawingPane;
    private javax.swing.JPanel LocationPane;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JPanel ModeStatusBar;
    private javax.swing.JTabbedPane PropertiesPane;
    private javax.swing.JPanel ShapeAction2DContainerPane;
    private javax.swing.JPanel ShapeAction3DContainerPane;
    private javax.swing.JPanel ShapeActionContainerPane;
    private javax.swing.JPanel SpeedPane;
    private javax.swing.JPanel SttBar;
    private javax.swing.JPanel XLocation;
    private javax.swing.JPanel YLocation;
    private javax.swing.JMenuItem _2DMenuItem;
    private javax.swing.JMenuItem _3DMenuItem;
    private javax.swing.JPanel actionChoosingBar;
    private javax.swing.JButton btnCar;
    private javax.swing.JButton btnCube;
    private javax.swing.JButton btnGrid;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnPyramid;
    private javax.swing.JButton btnQtmInfo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lblLocationXLabel;
    private javax.swing.JLabel lblLocationYLabel;
    private javax.swing.JLabel lblModeStatus;
    private javax.swing.JLabel lblModeStatusValue;
    private javax.swing.JLabel lblSpeedFPMs;
    private javax.swing.JMenu mbFileMenu;
    private javax.swing.JMenu mbModeMenu;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JPanel separator;
    private javax.swing.JPanel shapesChoosingBar;
    private javax.swing.JSlider sldSpeed;
    private javax.swing.JPanel tab2;
    private javax.swing.JPanel tabCar;
    private javax.swing.JTextField txtFLocationXValue;
    private javax.swing.JTextField txtFLocationYValue;
    // End of variables declaration//GEN-END:variables
    // </editor-fold>
}

