/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package computergraphics;

import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.Shape;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.awt.image.ImageObserver;
import java.io.File;
import java.io.IOException;
import java.text.AttributedCharacterIterator;
import java.util.ArrayList;
import java.util.EventListener;
import javax.imageio.ImageIO;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.KeyStroke;
import javax.swing.Timer;
import javax.swing.UIManager;


/**
 *
 * @author AnThien049
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {       
        settingUpContentPaneBackground();
        initComponents();           
        System.out.println(this.jLayeredPane1.getSize());
        System.out.println(this.DrawingPane2D.getSize());
        System.out.println(this.DrawingPane3D.getSize());
        System.out.println(this.getSize());
        try  {
            settingUpSomeFunctionalities();
            customMenubar();
            customChoosingShapesBar();
            customStatusBar();
        } catch (Exception e){  
            System.out.println(e);
        }           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnCar = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();
        SttBar = new javax.swing.JPanel()
        {
            @Override
            public void paintComponent(Graphics g) 
            {
                super.paintComponent(g);
                g.setColor(Color.WHITE);
                g.setFont(new Font("HACKED", Font.BOLD, 14));
                g.drawString("Hello From D17DQCN01", grtLocation, 22);
            }
        };
        btnQtmInfo = new javax.swing.JButton();
        ModeStatusBar = new javax.swing.JPanel();
        lblModeStatus = new javax.swing.JLabel();
        lblModeStatusValue = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        DrawingPane2D = new javax.swing.JPanel()
        {
            @Override
            public void paintComponent(Graphics g) 
            {
                super.paintComponent(g);
                if(start == true)
                {
                    //newCar = new Car(new Point(location, 250));        
                    DrawCar draw = new DrawCar(newCar);
                    draw.drawing((Graphics2D)g, Color.RED);
                }
            }
        };
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        DrawingPane3D = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PropertiesPane = new javax.swing.JTabbedPane();
        tab1 = new javax.swing.JPanel();
        LocationPane = new javax.swing.JPanel();
        XLocation = new javax.swing.JPanel();
        lblLocationXLabel = new javax.swing.JLabel();
        lblLocationXValue = new javax.swing.JLabel();
        YLocation = new javax.swing.JPanel();
        lblLocationYLabel = new javax.swing.JLabel();
        lblLocationYValue = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        mbFileMenu = new javax.swing.JMenu();
        saveMenuItem = new javax.swing.JMenuItem();
        mbModeMenu = new javax.swing.JMenu();
        _2DMenuItem = new javax.swing.JMenuItem();
        _3DMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Computer Graphics");
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        btnCar.setBorderPainted(false);
        btnCar.setContentAreaFilled(false);
        btnCar.setFocusPainted(false);
        btnCar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCarMouseClicked(evt);
            }
        });
        btnCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnPlay.setToolTipText("S");
        btnPlay.setBorderPainted(false);
        btnPlay.setContentAreaFilled(false);
        btnPlay.setFocusable(false);
        btnPlay.setMaximumSize(new java.awt.Dimension(40, 40));
        btnPlay.setMinimumSize(new java.awt.Dimension(40, 40));
        btnPlay.setPreferredSize(new java.awt.Dimension(40, 40));
        btnPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlayMouseClicked(evt);
            }
        });

        SttBar.setBackground(new java.awt.Color(0, 122, 204));
        SttBar.setLayout(null);

        btnQtmInfo.setToolTipText("Information");
        btnQtmInfo.setBorderPainted(false);
        btnQtmInfo.setContentAreaFilled(false);
        btnQtmInfo.setFocusable(false);
        btnQtmInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQtmInfoMouseClicked(evt);
            }
        });
        SttBar.add(btnQtmInfo);
        btnQtmInfo.setBounds(978, 5, 22, 20);

        ModeStatusBar.setBackground(new java.awt.Color(0, 122, 204));
        ModeStatusBar.setForeground(new java.awt.Color(255, 255, 255));
        ModeStatusBar.setToolTipText("Current dimensional mode");
        ModeStatusBar.setPreferredSize(new java.awt.Dimension(90, 16));
        java.awt.GridBagLayout StatusBarLayout = new java.awt.GridBagLayout();
        StatusBarLayout.rowWeights = new double[] {10.0};
        ModeStatusBar.setLayout(StatusBarLayout);

        lblModeStatus.setBackground(new java.awt.Color(0, 0, 0));
        lblModeStatus.setForeground(new java.awt.Color(255, 255, 255));
        lblModeStatus.setText("Mode status:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 0, 2);
        ModeStatusBar.add(lblModeStatus, gridBagConstraints);

        lblModeStatusValue.setBackground(new java.awt.Color(0, 0, 0));
        lblModeStatusValue.setForeground(new java.awt.Color(255, 255, 255));
        lblModeStatusValue.setText("2D");
        lblModeStatusValue.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 0, 0);
        ModeStatusBar.add(lblModeStatusValue, gridBagConstraints);

        SttBar.add(ModeStatusBar);
        ModeStatusBar.setBounds(798, 7, 92, 16);

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(800, 500));
        jLayeredPane1.setLayout(new java.awt.CardLayout());

        DrawingPane2D.setBackground(new java.awt.Color(255, 255, 255));
        DrawingPane2D.setPreferredSize(new java.awt.Dimension(800, 500));

        jLabel2.setText("TAB 2D");

        javax.swing.GroupLayout DrawingPane2DLayout = new javax.swing.GroupLayout(DrawingPane2D);
        DrawingPane2D.setLayout(DrawingPane2DLayout);
        DrawingPane2DLayout.setHorizontalGroup(
            DrawingPane2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DrawingPane2DLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
            .addGroup(DrawingPane2DLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(378, Short.MAX_VALUE))
        );
        DrawingPane2DLayout.setVerticalGroup(
            DrawingPane2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DrawingPane2DLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addGroup(DrawingPane2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        jLayeredPane1.add(DrawingPane2D, "card2");

        DrawingPane3D.setBackground(new java.awt.Color(255, 255, 255));
        DrawingPane3D.setPreferredSize(new java.awt.Dimension(800, 500));

        jLabel1.setText("TAB 3D");

        javax.swing.GroupLayout DrawingPane3DLayout = new javax.swing.GroupLayout(DrawingPane3D);
        DrawingPane3D.setLayout(DrawingPane3DLayout);
        DrawingPane3DLayout.setHorizontalGroup(
            DrawingPane3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DrawingPane3DLayout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(227, Short.MAX_VALUE))
        );
        DrawingPane3DLayout.setVerticalGroup(
            DrawingPane3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DrawingPane3DLayout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.add(DrawingPane3D, "card3");

        PropertiesPane.setBackground(new java.awt.Color(39, 45, 48));
        PropertiesPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Properties", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("VNI-Whimsy", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        PropertiesPane.setForeground(new java.awt.Color(39, 45, 48));

        tab1.setBackground(new java.awt.Color(255, 255, 255));
        tab1.setForeground(new java.awt.Color(0, 0, 0));

        LocationPane.setBackground(new java.awt.Color(255, 255, 255));
        LocationPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Location", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        LocationPane.setForeground(new java.awt.Color(0, 0, 0));

        XLocation.setBackground(new java.awt.Color(255, 255, 255));
        XLocation.setForeground(new java.awt.Color(0, 0, 0));
        XLocation.setLayout(new java.awt.GridBagLayout());

        lblLocationXLabel.setBackground(new java.awt.Color(255, 255, 255));
        lblLocationXLabel.setForeground(new java.awt.Color(0, 0, 0));
        lblLocationXLabel.setText("X :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 10.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 0);
        XLocation.add(lblLocationXLabel, gridBagConstraints);

        lblLocationXValue.setBackground(new java.awt.Color(255, 255, 255));
        lblLocationXValue.setForeground(new java.awt.Color(0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 49);
        XLocation.add(lblLocationXValue, gridBagConstraints);

        YLocation.setBackground(new java.awt.Color(255, 255, 255));
        YLocation.setForeground(new java.awt.Color(0, 0, 0));
        YLocation.setLayout(new java.awt.GridBagLayout());

        lblLocationYLabel.setBackground(new java.awt.Color(255, 255, 255));
        lblLocationYLabel.setForeground(new java.awt.Color(0, 0, 0));
        lblLocationYLabel.setText("Y :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 10.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 0);
        YLocation.add(lblLocationYLabel, gridBagConstraints);

        lblLocationYValue.setBackground(new java.awt.Color(255, 255, 255));
        lblLocationYValue.setForeground(new java.awt.Color(0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 49);
        YLocation.add(lblLocationYValue, gridBagConstraints);

        javax.swing.GroupLayout LocationPaneLayout = new javax.swing.GroupLayout(LocationPane);
        LocationPane.setLayout(LocationPaneLayout);
        LocationPaneLayout.setHorizontalGroup(
            LocationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LocationPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(XLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(YLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        LocationPaneLayout.setVerticalGroup(
            LocationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(XLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(YLocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout tab1Layout = new javax.swing.GroupLayout(tab1);
        tab1.setLayout(tab1Layout);
        tab1Layout.setHorizontalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LocationPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab1Layout.setVerticalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LocationPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PropertiesPane.addTab("Car", tab1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        PropertiesPane.addTab("tab2", jPanel1);

        jButton1.setText("Click me");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        mbFileMenu.setText("File");
        mbFileMenu.setToolTipText("Some specific tasks");

        saveMenuItem.setText("Save");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        mbFileMenu.add(saveMenuItem);

        MenuBar.add(mbFileMenu);

        mbModeMenu.setText("Mode");
        mbModeMenu.setToolTipText("Select dimensional mode");

        _2DMenuItem.setText("2D");
        _2DMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _2DMenuItemActionPerformed(evt);
            }
        });
        mbModeMenu.add(_2DMenuItem);

        _3DMenuItem.setText("3D");
        _3DMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _3DMenuItemActionPerformed(evt);
            }
        });
        mbModeMenu.add(_3DMenuItem);

        MenuBar.add(mbModeMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SttBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(btnClear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PropertiesPane))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnClear)
                                .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PropertiesPane, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addComponent(SttBar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="Components Action Performing"> 
    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        JOptionPane.showMessageDialog(this, "wanna save?", "Save", JOptionPane.QUESTION_MESSAGE);
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void _2DMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__2DMenuItemActionPerformed
        this.lblModeStatusValue.setText("2D");
        this.DrawingPane2D.setVisible(true);
        this.DrawingPane3D.setVisible(false);    
    }//GEN-LAST:event__2DMenuItemActionPerformed

    private void _3DMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__3DMenuItemActionPerformed
        this.lblModeStatusValue.setText("3D");
        this.DrawingPane3D.setVisible(true);
        this.DrawingPane2D.setVisible(false);
    }//GEN-LAST:event__3DMenuItemActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearDrawingPanel();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarActionPerformed
        System.out.println("??");      
        if (start == true) {
            newCar = new Car(new Point(location, yStarted));
            this.lblLocationXValue.setText(String.valueOf((int)newCar.get1stPoint().getX()));
            this.lblLocationYValue.setText(String.valueOf((int)newCar.get1stPoint().getY()));
            System.out.println(location);
            if (runBack == true) {                
                this.DrawingPane2D.repaint();
                location -= step;
                if (location == startingLocation) {
                    runBack = false;
                }
            } else {
                this.DrawingPane2D.repaint();
                location += step;
                if (location == stopLocation) {
                    runBack = true;
                }
            }
        }                
    }//GEN-LAST:event_btnCarActionPerformed
    
    private void btnCarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCarMouseClicked
        if (start == false) {  
            start = true;
            location = startingLocation;
            newCar = new Car(new Point(location, yStarted));
            this.DrawingPane2D.repaint();
            this.lblLocationXValue.setText(String.valueOf((int)newCar.get1stPoint().getX()));
            this.lblLocationYValue.setText(String.valueOf((int)newCar.get1stPoint().getY()));
            location += step;   
            exist = true;
    }//GEN-LAST:event_btnCarMouseClicked
}
    private void btnPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayMouseClicked
        if(start == false || exist == true){
            start = true;
            timer = new Timer(timerDelay, this.btnCar.getActionListeners()[0]);
            timer.start();     
            exist = false;
        } else if (start == true) {
            start = false;          
            timer.stop(); 
        }
        changePlayStopIcon();
    }//GEN-LAST:event_btnPlayMouseClicked

    private void btnQtmInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQtmInfoMouseClicked
        UIManager.put("OptionPane.messageFont", new Font("VNF-Valentina", Font.PLAIN, 15));
        UIManager.put("OptionPane.buttonFont", new Font("VNF-Valentina", Font.PLAIN, 15));       
        UIManager.put("OptionPane.messageDialog.titlePane.background", Color.black);
//        JOptionPane.showMessageDialog(this, "N17DCCN008  Đinh Nguyễn Thiên Ân \n" 
//                                          + "N17DCCN013   Nguyễn Mạnh Bình \n"
//                                          + "N17DCCN042  Phạm Phan Đại Hải \n"
//                                          + "N17DCCN053  Trương Minh Hoàng \n"
//                                          + "N17DCCN056  Nguyễn Ngọc Huy",
//                                     "Thành Viên", JOptionPane.INFORMATION_MESSAGE, scaledPePeIcon);
        
        JOptionPane op = new JOptionPane("N17DCCN008  Đinh Nguyễn Thiên Ân \n" 
                                       + "N17DCCN013   Nguyễn Mạnh Bình \n"
                                       + "N17DCCN042  Phạm Phan Đại Hải \n"
                                       + "N17DCCN053  Trương Minh Hoàng \n"
                                       + "N17DCCN056  Nguyễn Ngọc Huy"
                                       ,JOptionPane.INFORMATION_MESSAGE, JOptionPane.DEFAULT_OPTION, scaledPePeIcon); 
        op.setBackground(Color.WHITE);
        getComponents(op);
        JDialog dialog = op.createDialog(this, "Thành Viên");
        dialog.setAlwaysOnTop(true);
        dialog.setModal(false);
        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);      
        dialog.setVisible(true);
    }//GEN-LAST:event_btnQtmInfoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        gottaSeeitManxD();
    }//GEN-LAST:event_jButton1ActionPerformed
    // </editor-fold>          
    
    // <editor-fold defaultstate="collapsed" desc="Components Customizing"> 
    
    /**
     * Custom menu bar 
     */
    public void customMenubar() throws IOException
    {
        /**
        * File menu 
        */
        this.mbFileMenu.setMnemonic(KeyEvent.VK_F);
        
        /**
        * File menu item: save
        */      
        ImageIcon icon = new ImageIcon("images/save_icon.png");
        Image image = icon.getImage();
        Image newImg = image.getScaledInstance(20, 20, java.awt.Image.SCALE_SMOOTH); 
        ImageIcon scaledSaveIcon = new ImageIcon(newImg);
        this.saveMenuItem.setIcon(scaledSaveIcon);
        this.saveMenuItem.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_S, KeyEvent.CTRL_DOWN_MASK));
        
        /**
        * Mode menu
        */
        this.mbModeMenu.setMnemonic(KeyEvent.VK_M);
        
        /**
        * Mode menu item: 2D
        */
        icon = new ImageIcon("images/2D_coordinate.png");
        image = icon.getImage();
        newImg = image.getScaledInstance(30, 30, java.awt.Image.SCALE_SMOOTH); 
        ImageIcon scaled2DIcon = new ImageIcon(newImg);
        this._2DMenuItem.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_2, KeyEvent.CTRL_DOWN_MASK));
        this._2DMenuItem.setIcon(scaled2DIcon);
        
        /**
        * Mode menu item: 3D
        */
        icon = new ImageIcon("images/3D_coordinate.png");
        image = icon.getImage(); 
        newImg = image.getScaledInstance(30, 30, java.awt.Image.SCALE_SMOOTH);  
        ImageIcon scaled3DIcon = new ImageIcon(newImg);
        this._3DMenuItem.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_3, KeyEvent.CTRL_DOWN_MASK));
        this._3DMenuItem.setIcon(scaled3DIcon);
    }
    
    /**
     * Custom shapes-choosing bar 
     */
    public void customChoosingShapesBar()
    {
        ImageIcon icon = new ImageIcon("images/car_icon.png");
        Image image = icon.getImage();
        Image newImg = image.getScaledInstance(this.btnCar.getWidth(), this.btnCar.getHeight(), java.awt.Image.SCALE_SMOOTH); 
        ImageIcon scaled3DIcon = new ImageIcon(newImg);
        this.btnCar.setIcon(scaled3DIcon);
        
        icon = new ImageIcon("images/play_icon.png");
        image = icon.getImage();
        newImg = image.getScaledInstance(this.btnPlay.getWidth(), this.btnPlay.getHeight(), java.awt.Image.SCALE_SMOOTH); 
        scaledPlayIcon = new ImageIcon(newImg);
        this.btnPlay.setIcon(scaledPlayIcon);
        
        icon = new ImageIcon("images/stop_icon.png");
        image = icon.getImage();
        newImg = image.getScaledInstance(this.btnPlay.getWidth(), this.btnPlay.getHeight(), java.awt.Image.SCALE_SMOOTH); 
        scaledStopIcon = new ImageIcon(newImg);
    }
    
    /**
     * Custom status bar 
     */
    public void customStatusBar()
    {
        ImageIcon icon = new ImageIcon("images/question_mark_icon.png");
        Image image = icon.getImage();
        Image newImg = image.getScaledInstance(this.btnQtmInfo.getWidth(), this.btnQtmInfo.getHeight(), java.awt.Image.SCALE_SMOOTH); 
        ImageIcon scaledQMIcon = new ImageIcon(newImg);
        this.btnQtmInfo.setIcon(scaledQMIcon);
        this.btnQtmInfo.setMnemonic(KeyEvent.VK_SLASH);  
        
        icon = new ImageIcon("images/meme28.png");
        image = icon.getImage();
        newImg = image.getScaledInstance(50, 50, java.awt.Image.SCALE_SMOOTH); 
        scaledPePeIcon = new ImageIcon(newImg);
    }
    
    /**
     * Custom some initialized components properties & functionalities
     */
    public void settingUpContentPaneBackground()
    {
        /**
        * Setting up some properties for main window
        */
        //this.getContentPane().setBackground(new Color(60, 63, 65)); // Set màu nền của contentPane của frame
        try{
            BufferedImage myImage = ImageIO.read(new File("images/bg.jpg"));
            Image myyImage = myImage.getScaledInstance(1021, 669, java.awt.Image.SCALE_SMOOTH); 
            this.setContentPane(new BackgroundImage(myyImage));      
        } catch(Exception e){System.out.println(e);}
    }
    
    public void settingUpSomeFunctionalities()
    {
      /**
        * Timer for some animations
        */
//        ActionListener greetingAction = new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent arg0) {
//                greeting();
//            }
//        };
//        
//        greetingTimer = new Timer(20, greetingAction);
//        greetingTimer.start();
         
        greetingTimer = new Timer(10, new ActionListener(){    //Câu chào ở thanh status animation
        public void actionPerformed(ActionEvent e) {
            greeting();
        }
        });
        greetingTimer.start();
        
        /**
        * Key Binding for some functionalities
        */
        KeyStroke escapeKeyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0, false); //ESC để quit
        Action escapeAction = new AbstractAction() {
           public void actionPerformed(ActionEvent e) {
               // dispose();
                System.exit(0);
           }
        }; 
        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(escapeKeyStroke, "ESCAPE");
        this.getRootPane().getActionMap().put("ESCAPE", escapeAction);
        
        KeyStroke playStopKeyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_S, 0);  //S để play/stop animation
        Action playStopAction = new AbstractAction() {
           public void actionPerformed(ActionEvent e) {
                MouseEvent mEvt = null;
                btnPlayMouseClicked(mEvt);
           }    
        }; 
        this.btnPlay.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(playStopKeyStroke, "PLAYSTOP");
        this.btnPlay.getActionMap().put("PLAYSTOP", playStopAction);
        
        KeyStroke drawCarKeyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_C, 0);  //C để vẽ xe tĩnh
        Action drawCarAction = new AbstractAction() {
           public void actionPerformed(ActionEvent e) {
                MouseEvent mEvt = null;
                btnCarMouseClicked(mEvt);
           }    
        }; 
        this.btnCar.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(drawCarKeyStroke, "STATICDRAW");
        this.btnCar.getActionMap().put("STATICDRAW", drawCarAction);
        
        KeyStroke memberInfoKeyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_SLASH, 0);  //nhấn /(?) để hiển thị thông tin thành viên
        Action memberInfoAction = new AbstractAction() {
           public void actionPerformed(ActionEvent e) {
                MouseEvent mEvt = null;
                btnQtmInfoMouseClicked(mEvt);
           }    
        }; 
        this.btnCar.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(memberInfoKeyStroke, "SHOWINFO");
        this.btnCar.getActionMap().put("SHOWINFO", memberInfoAction);
    }  
    
    /**
     * Some required processing for those above or just additional functionalities
     */
    public void clearDrawingPanel() // Làm mới drawing panel xóa ds các đối tượng đã được vẽ
    {
        Graphics2D grp = (Graphics2D)this.DrawingPane2D.getGraphics();
        grp.setBackground(Color.WHITE);    
    }
    
    public void changePlayStopIcon()
    {
        if(start == true){
            this.btnPlay.setIcon(scaledStopIcon);
        }else{
            this.btnPlay.setIcon(scaledPlayIcon);
        }     
    }
    
    public void greeting()
    {
        if (grtRunBack == true) {
            this.SttBar.repaint();
            grtLocation -= step;
            if (grtLocation == 10) {
                grtRunBack = false;
            }
        } else {
            this.SttBar.repaint();
            grtLocation += step;
            if (grtLocation == 633) {
                grtRunBack = true;
            }
        }  
    }
    
    public void getComponents(Container c) {
        Component[] m = c.getComponents();
        for (int i = 0; i < m.length; i++) {
            if (m[i].getClass().getName() == "javax.swing.JPanel")
            {
                m[i].setBackground(Color.WHITE);
            }
           // if (c.getClass().isInstance(m[i])) 
            getComponents((Container) m[i]);
        }
    }
    
    public void gottaSeeitManxD()
    {
        if(this.jLayeredPane1.isVisible()){
            this.jLayeredPane1.setVisible(false);
            this.PropertiesPane.setVisible(false);
        }else{
            this.jLayeredPane1.setVisible(true);
            this.PropertiesPane.setVisible(true);
        }
            
    }
    
    // </editor-fold> 
     
    // <editor-fold defaultstate="collapsed" desc="Global User-defined variables declaration">
    int location = 20;
    int startingLocation = 20;
    int stopLocation = 350;
    int step = 1;   
    int timerDelay = 5; 
    int yStarted = 250;
    boolean start = false;
    boolean runBack = false;
    boolean exist = false;
    Timer timer = null;
    
    int grtLocation = 3;
    boolean grtRunBack = false; 
    Timer greetingTimer;
     
    ImageIcon scaledStopIcon = null;
    ImageIcon scaledPlayIcon = null;
    ImageIcon scaledPePeIcon = null;
    
    Car newCar;
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Global application variables declaration">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DrawingPane2D;
    private javax.swing.JPanel DrawingPane3D;
    private javax.swing.JPanel LocationPane;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JPanel ModeStatusBar;
    private javax.swing.JTabbedPane PropertiesPane;
    private javax.swing.JPanel SttBar;
    private javax.swing.JPanel XLocation;
    private javax.swing.JPanel YLocation;
    private javax.swing.JMenuItem _2DMenuItem;
    private javax.swing.JMenuItem _3DMenuItem;
    private javax.swing.JButton btnCar;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnQtmInfo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblLocationXLabel;
    private javax.swing.JLabel lblLocationXValue;
    private javax.swing.JLabel lblLocationYLabel;
    private javax.swing.JLabel lblLocationYValue;
    private javax.swing.JLabel lblModeStatus;
    private javax.swing.JLabel lblModeStatusValue;
    private javax.swing.JMenu mbFileMenu;
    private javax.swing.JMenu mbModeMenu;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JPanel tab1;
    // End of variables declaration//GEN-END:variables
    // </editor-fold>
}

